TASK_NLU_PARSE_TEXT = "nlu-parse-text"
TASK_NLU_DEBUG_PARSE_TEXT = "nlu-debug-parse-text"
TASK_NLU_SENTENCE_SUGGESTION_TEXT = "nlu-sentence-suggestion-text"
TASK_NLU_WORDS_DISTRIBUTION = "nlu-words-distribution"
TASK_NLU_SCORE_CALCULATION = "nlu-score-calculation"
TASK_NLU_TRAIN_UPDATE = "nlu-train-update"
TASK_NLU_EVALUATE_UPDATE = "nlu-evaluate-update"
